AWSTemplateFormatVersion: "2010-09-09"

Description: "AWS CloudFormation template to create DynamoDB stack"
Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "db-todolist"
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "task_id"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema: # Required
        - AttributeName: "user_id"
          KeyType: "HASH"
        - AttributeName: "task_id"
          KeyType: "RANGE"


Outputs:
  DynamoTableArn:
    Value: !GetAtt DynamoTable.Arn