AWSTemplateFormatVersion: "2010-09-09"

Description: "AWS CloudFormation template to create resources stacks"

Parameters:
  TemplatesBucketName:
    Type: String
    Description: 'Name of the S3 bucket where the templates resources are stored'
    Default: cfn-templates-todolist-app

Resources:
  S3CloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/S3-CloudFront.yaml
  
  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/cognito.yaml
      Parameters:
        CloudFrontURL: !GetAtt S3CloudFront.Outputs.CloudFrontDistributionURL

  LambdaDynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/lambda-Dynamo.yaml
      
  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/apigateway.yaml
      Parameters:
        CognitoUserPoolArn: !GetAtt Cognito.Outputs.CongnitoUserPoolArn
        TodoLambdaArn: LambdaDynamoDB.Outputs.TodoLambdaArn