AWSTemplateFormatVersion: "2010-09-09"

Description: "AWS CloudFormation template to create resources stacks"

Parameters:
  TemplatesBucketName:
    Type: String
    Description: 'Name of the S3 bucket where the templates resources are stored'
    Default: cfn-templates-todolist-app

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/websiteS3Bucket.yaml
  
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/cognito.yaml
      Parameters:
        CloudFrontURL: !GetAtt CloudFrontStack.Outputs.CloudFrontDistributionURL

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/cloudFront.yaml
      Parameters:
        WebSiteS3Bucket: !GetAtt S3Stack.Outputs.S3BucketFrontendName