AWSTemplateFormatVersion: "2010-09-09"

Description: "AWS CloudFormation template to created S3 bucket and CloudFront services"

Resources:
  S3BucketFrontEnd:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'frontend-resources-todolist'
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  

  BucketOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "My OAI config for my todolist website"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketFrontEnd
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${BucketOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3BucketFrontEnd}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt S3BucketFrontEnd.DomainName
            Id: s3-bucket-frontend
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${BucketOAI}"
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: s3-bucket-frontend
          ViewerProtocolPolicy: allow-all
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
        PriceClass: PriceClass_All

Outputs:
  CloudFrontDistributionURL:
    Description: "URL of the CloudFront distribution"
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebsiteOAI:
    Description: "OAI for the website"
    Value: !Ref BucketOAI