# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - template-pipeline.yml

pool:
  vmImage: ubuntu-latest

steps:
  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws'
      regionName: '$(REGION)'
      bucketName: '$(BUCKET_NAME)'
      sourceFolder: './'
      globExpressions: |
        **
        !*.yml
        !.git/**
      createBucket: true
      
  - task: CloudFormationCreateOrUpdateStack@1
    inputs:
      awsCredentials: 'aws'
      regionName: '$(REGION)'
      stackName: 'website-deploy'
      templateSource: 's3'
      s3BucketName: '$(BUCKET_NAME)'
      s3ObjectKey: 'main.yaml'
      capabilityAutoExpand: true
